// Define an object of keywords and their corresponding Wikipedia URLs
const keywordToUrlMap = {
    'science': 'https://en.wikipedia.org/wiki/Science',
    'art': 'https://en.wikipedia.org/wiki/Art',
    'literature': 'https://en.wikipedia.org/wiki/Literature',
    'religion': 'https://en.wikipedia.org/wiki/Religion',
    'philosophy': 'https://en.wikipedia.org/wiki/Philosophy',
    'history': 'https://en.wikipedia.org/wiki/History',
    'technology': 'https://en.wikipedia.org/wiki/Technology',
    'music': 'https://en.wikipedia.org/wiki/Music',
    'space': 'https://en.wikipedia.org/wiki/Outer_space',
    'nature': 'https://en.wikipedia.org/wiki/Nature',
    'culture': 'https://en.wikipedia.org/wiki/Culture',
    'politics': 'https://en.wikipedia.org/wiki/Politics',
    'economics': 'https://en.wikipedia.org/wiki/Economics',
    'society': 'https://en.wikipedia.org/wiki/Society',
    'education': 'https://en.wikipedia.org/wiki/Education',
    'health': 'https://en.wikipedia.org/wiki/Health',
    'food': 'https://en.wikipedia.org/wiki/Food',
    'sports': 'https://en.wikipedia.org/wiki/Sport',
    'nasa': 'https://en.wikipedia.org/wiki/NASA',
    'earth': 'https://en.wikipedia.org/wiki/Earth',
    'human': 'https://en.wikipedia.org/wiki/Human',
    'marcus aurelius': 'https://en.wikipedia.org/wiki/Marcus_Aurelius',
    'stoicism': 'https://en.wikipedia.org/wiki/Stoicism',
    'epictetus': 'https://en.wikipedia.org/wiki/Epictetus',
    'seneca the younger': 'https://en.wikipedia.org/wiki/Seneca_the_Younger',
    'socrates': 'https://en.wikipedia.org/wiki/Socrates',
    'plato': 'https://en.wikipedia.org/wiki/Plato',
    'android': 'https://en.wikipedia.org/wiki/Android_(operating_system)',
    'ios': 'https://en.wikipedia.org/wiki/IOS',
    'linux': 'https://en.wikipedia.org/wiki/Linux',
    'windows': 'https://en.wikipedia.org/wiki/Microsoft_Windows',
    'macos': 'https://en.wikipedia.org/wiki/MacOS',
    'java': 'https://en.wikipedia.org/wiki/Java_(programming_language)',
    'python': 'https://en.wikipedia.org/wiki/Python_(programming_language)',
    'javascript': 'https://en.wikipedia.org/wiki/JavaScript',
    'html': 'https://en.wikipedia.org/wiki/HTML',
    'css': 'https://en.wikipedia.org/wiki/CSS',
    'sql': 'https://en.wikipedia.org/wiki/SQL',
    'php': 'https://en.wikipedia.org/wiki/PHP',
    'ruby': 'https://en.wikipedia.org/wiki/Ruby_(programming_language)',
    'c++': 'https://en.wikipedia.org/wiki/C%2B%2B',
    'c#': 'https://en.wikipedia.org/wiki/C_Sharp_(programming_language)',
    'go': 'https://en.wikipedia.org/wiki/Go_(programming_language)',
    'swift': 'https://en.wikipedia.org/wiki/Swift_(programming_language)',
    'kotlin': 'https://en.wikipedia.org/wiki/Kotlin_(programming_language)',
    'r': 'https://en.wikipedia.org/wiki/R_(programming_language)',
    'typescript': 'https://en.wikipedia.org/wiki/TypeScript',
    'perl': 'https://en.wikipedia.org/wiki/Perl',
    'scala': 'https://en.wikipedia.org/wiki/Scala_(programming_language)',
    'rust': 'https://en.wikipedia.org/wiki/Rust_(programming_language)',
    'haskell': 'https://en.wikipedia.org/wiki/Haskell_(programming_language)',
    'assembly': 'https://en.wikipedia.org/wiki/Assembly_language',
    'bash': 'https://en.wikipedia.org/wiki/Bash_(Unix_shell)',
    'powershell': 'https://en.wikipedia.org/wiki/PowerShell',
    'git': 'https://en.wikipedia.org/wiki/Git',
    'docker': 'https://en.wikipedia.org/wiki/Docker_(software)',
    'kubernetes': 'https://en.wikipedia.org/wiki/Kubernetes',
    'jenkins': 'https://en.wikipedia.org/wiki/Jenkins_(software)',
    'apache': 'https://en.wikipedia.org/wiki/Apache_HTTP_Server',
    'nginx': 'https://en.wikipedia.org/wiki/Nginx',
    'mysql': 'https://en.wikipedia.org/wiki/MySQL',
    'postgresql': 'https://en.wikipedia.org/wiki/PostgreSQL',
    'mongodb': 'https://en.wikipedia.org/wiki/MongoDB',
    'redis': 'https://en.wikipedia.org/wiki/Redis',
    'cassandra': 'https://en.wikipedia.org/wiki/Apache_Cassandra',
    'elasticsearch': 'https://en.wikipedia.org/wiki/Elasticsearch',
    'rabbitmq': 'https://en.wikipedia.org/wiki/RabbitMQ',
    'kafka': 'https://en.wikipedia.org/wiki/Apache_Kafka',
    'zookeeper': 'https://en.wikipedia.org/wiki/Apache_ZooKeeper',
    'spark': 'https://en.wikipedia.org/wiki/Apache_Spark',
    'hadoop': 'https://en.wikipedia.org/wiki/Apache_Hadoop',
    'flink': 'https://en.wikipedia.org/wiki/Apache_Flink',
    'couchbase': 'https://en.wikipedia.org/wiki/Couchbase',
    'memcached': 'https://en.wikipedia.org/wiki/Memcached',
    'couchdb': 'https://en.wikipedia.org/wiki/CouchDB',
    'neo4j': 'https://en.wikipedia.org/wiki/Neo4j',
    'dynamodb': 'https://en.wikipedia.org/wiki/Amazon_DynamoDB',
    'firebase': 'https://en.wikipedia.org/wiki/Firebase',
    'azure': 'https://en.wikipedia.org/wiki/Microsoft_Azure',
    'aws': 'https://en.wikipedia.org/wiki/Amazon_Web_Services',
    'apple': 'https://en.wikipedia.org/wiki/Apple_Inc.',
    'google': 'https://en.wikipedia.org/wiki/Google',
    'microsoft': 'https://en.wikipedia.org/wiki/Microsoft',
    'facebook': 'https://en.wikipedia.org/wiki/Facebook',
    'twitter': 'https://en.wikipedia.org/wiki/Twitter',
    'elon musk': 'https://en.wikipedia.org/wiki/Elon_Musk',
    'jeff bezos': 'https://en.wikipedia.org/wiki/Jeff_Bezos',
    'motorcycle': 'https://en.wikipedia.org/wiki/Motorcycle',
    'roam-electric-scooter': 'https://en.wikipedia.org/wiki/Roam_Electric_Scooter',
    'bicycle': 'https://en.wikipedia.org/wiki/Bicycle',
    'car': 'https://en.wikipedia.org/wiki/Car',
    'bus': 'https://en.wikipedia.org/wiki/Bus',
    'tesla': 'https://en.wikipedia.org/wiki/Tesla,_Inc.',
    'green-energy': 'https://en.wikipedia.org/wiki/Renewable_energy',
    'solar-energy': 'https://en.wikipedia.org/wiki/Solar_energy',
    'wind-energy': 'https://en.wikipedia.org/wiki/Wind_power',
    'hydro-energy': 'https://en.wikipedia.org/wiki/Hydroelectricity',
    'nuclear-energy': 'https://en.wikipedia.org/wiki/Nuclear_power',
    'coal-energy': 'https://en.wikipedia.org/wiki/Coal',
    'documentary': 'https://en.wikipedia.org/wiki/Documentary_film',
    'movie': 'https://en.wikipedia.org/wiki/Film',
    'surrender-a-galaxy': "https://solarmovies.win/movie/watch-never-surrender-a-galaxy-quest-documentary-online-66758",
    'minimalism': "https://solarmovies.win/movie/watch-minimalism-a-documentary-about-the-important-things-online-11171",
    'the-social-dilemma': "https://solarmovies.win/movie/watch-the-social-dilemma-online-11171",
    'the-great-hack': "https://solarmovies.win/movie/watch-the-great-hack-online-11171",
    'the-true-cost': "https://solarmovies.win/movie/watch-the-true-cost-online-11171",
    'the-game-changers': "https://solarmovies.win/movie/watch-the-game-changers-online-11171",
    'cosmos': "https://solarmovies.win/movie/watch-cosmos-possible-worlds-online-11171",
    'our-planet': "https://solarmovies.win/movie/watch-our-planet-online-11171",
    'cosmos': "https://solarmovies.win/tv/watch-cosmos-online-38183",
    'spirituality': "https://www.enlightened-spirituality.org/",
    'christianity': "https://www.christianity.com/",
    'got-questions': "https://www.gotquestions.org/"

};

// Get the button element
const button = document.getElementById('redirect-button');

// Add a click event listener to the button
button.addEventListener('click', () => {
    // Get a random keyword from the keywordToUrlMap object
    const keywords = Object.keys(keywordToUrlMap);
    const randomIndex = Math.floor(Math.random() * keywords.length);
    const randomKeyword = keywords[randomIndex];

    // Redirect the user to the corresponding Wikipedia article
    window.location.href = keywordToUrlMap[randomKeyword];
});
